name: CI
on:
  push:
    branches:
      - main
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v1
      - run: pip install black
      - run: black --check .
      - name: If needed, commit black changes to a new pull request
        if: failure()
        run: |
          black .
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'          
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Format Python code with psf/black push"
          git push origin main --force
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: gpt3discord.py
          target: /home/gptbot/
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: conversation_starter_pretext.txt
          target: /home/gptbot/
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: image_optimizer_pretext.txt
          target: /home/gptbot/
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cogs
          remote: /home/gptbot/cogs
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: models
          remote: /home/gptbot/models
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: openers
          remote: /home/gptbot/openers
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: openers
          remote: /home/gptbot/services
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: copy file via ssh password (OAI)
        uses: appleboy/scp-action@master
        with:
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: gpt3discord.py
          target: /home/gptbotopenai/
      - name: copy file via ssh password (OAI)
        uses: appleboy/scp-action@master
        with:
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: conversation_starter_pretext.txt
          target: /home/gptbotopenai/
      - name: copy file via ssh password (OAI)
        uses: appleboy/scp-action@master
        with:
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: image_optimizer_pretext.txt
          target: /home/gptbotopenai/
      - name: Copy via ssh (OAI)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cogs
          remote: /home/gptbotopenai/cogs
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Copy via ssh (OAI)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: models
          remote: /home/gptbotopenai/models
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Copy via ssh (OAI)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: openers
          remote: /home/gptbotopenai/openers
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Copy via ssh (OAI)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: openers
          remote: /home/gptbotopenai/services
          host: 104.248.105.234
          username: root
          password: ${{ secrets.SSH_PASS }}
      - name: Restart bot!
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/gptbot
            kill -9 $(cat bot.pid)
            rm bot.pid
            screen -dmS GPTBot python3.9 gpt3discord.py
            cd /home/gptbotopenai
            kill -9 $(cat bot.pid)
            rm bot.pid
            screen -dmS GPTBotOpenAI python3.9 gpt3discord.py
            logout
            exit
          host: 104.248.105.234
          user: root
          pass: ${{ secrets.SSH_PASS}}
